<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0-windows</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TDM.Models\TDM.Models.csproj" />
    <ProjectReference Include="..\TDM.Core\TDM.Core.csproj" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="8.0.1" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
</Project>
